### ISSUE TITLE
No debug info on backend crash

### ISSUE THREAD

**Issue by altavir** [JavaEden/Orchid#133]
Just got a crash when trying to enter admin page with message `Sorry! There's been an error - please report it!`. No debug information on page or in console window, so no way to find out what is the problem.

Probably should log an error at least at console, but maybe also on page since it is debug run on local port.

Orchid version: 0.8.9
Launched via gradle runner.

**Comment by altavir** [comment]
No, still no messages in console window. I think it is the issue of gradle runner. It sometimes eats logs if not configured properly.

**Comment by cjbrooks12** [comment]
Logs from the browser are going to show up in the browser's console, not your local terminal. As it is, the NetlifyCMS is only partially functional, I'm waiting on netlify/netlify-cms#1169 to complete to be able to manage components and menus, and your front matter customizations might be lost when updating a page from NetlifyCMS until then.

Is the rest of the admin UI working? You should still be able to open the side-nav and "manage" panel to see everything you can work with even if the NetlifyCMS isn't working correctly, and that's what's most important in the admin area for local development.

**Comment by altavir** [comment]
Yes, everything else is working.

**Comment by cjbrooks12** [comment]
Alright, then I'm going to close this issue as it seems to be more related to NetlifyCMS than Orchid, but I will continue to investigate if there's anything Orchid is doing to cause an invalid NetlifyCMS configuration or otherwise causing the crashes. 

This might be an issue to raise in [netlify/netlify-cms](https://github.com/netlify/netlify-cms) as well if you can find anything more out about your specific crash.
