### ISSUE TITLE
[suggestion] Rule based configuration

### ISSUE THREAD

**Issue by altavir** [JavaEden/Orchid#137]
Add user-oriented API to add rules for indexing, collection creation, etc. Rules allow to build more flexible function-oriented user extensions than inheritance. Rules could be directly injected into context without any inheritance and then automatically retrieved by consumer like it suggested in #136.

An example of using rules is collection generation. Basically collection takes the stream of all indexed resources and the select those that should be present in the given collection (one rule for one collection). The rule class could look like this:
```kotlin
interface CollectionRule{
  val collectionId: String
  fun select(pages: List<OrchidPage>): List<OrchidPage>
}
```
Then it could be added to module like `register<CollectionRule>(CollectionRule("myPages"){...})`

The same could be done for indexing and some other plug-ins.

Rule-based configuration could be implemented without changes to core structure just like additional generator or even slight changes to default generators.

**Comment by cjbrooks12** [comment]
Rather than changing how Orchid handles the indexing/generating process to allow for rule-based configuration, this would make a great plugin that sits perfectly inside the existing process. Its a really great idea, and has a lot of foundations for a plugin I've been thinking about for a while. It could support registration of these Rules in a wide variety of different ways so as to be adaptable to any purpose, such as:

- Inject Rules directly from Module registration
- Create Rules based on end-user config in `config.yml`
- Fire events to dynamically request Rules, so that end-users can write scripts to set up their Rules. This event would be able to host a method like `register<CollectionRule>(CollectionRule("myPages"){...})` to allow for dynamic registration, unlike registering Rules directly on the OrchidContext.
