### ISSUE TITLE
Odd dependency on "American-Bible-Society-Client"

### ISSUE THREAD

**Issue by ericis** [JavaEden/Orchid#219]
There's an odd dependency on `American-Bible-Society-Client`. I haven't reviewed the hierarchy of code and dependencies, but this seems like a very odd one. I actually assumed there was some malware involved somehow, but this looks valid, but unnecessary.

**Comment by cjbrooks12** [comment]
No, it's intentional. It's part of the the [OrchidBible plugin](https://orchid.netlify.com/plugins/OrchidBible), which is included in the `Orchid-All` and `Orchid-Language-Pack` bundles. It's by no means necessary, and you are free to pick just the plugins you need to exclude the `io.github.javaeden.orchid:OrchidBible` dependency. 

The `OrchidBible` plugin was one of the earliest ones I added (based on an old library I wrote several years ago) and have just left it there in case anyone wants it. The `American-Bible-Society-Client` dependency is that old library.
