### ISSUE TITLE
this is really cool, why not a command line tool

### ISSUE THREAD

**Issue by ORESoftware** [JavaEden/Orchid#229]
Just curious, this project looks awesome, why not a command line tool + a config file? I wonder why we need maven deps per project?

**Comment by cjbrooks12** [comment]
The main reason for setting Orchid up using dependencies is to support it's plugin system, and because Orchid is best kept in the same repository as the main project, so it just makes sense to use the same build tooling and conventions as the rest of the project.

That being said, both the Gradle and Maven plugins are really just thin wrappers over it's internal CLI. If you set up your project using kscript, you can use the CLI directly: https://orchid.netlify.com/wiki/user-manual/getting-started/quickstart#kscript

My personal site is set up in this way. Kscript can even generate a stand-alone binary for better access to the CLI https://github.com/cjbrooks12/caseyjbrooks
