### ISSUE TITLE
Simple Java library docs

### ISSUE THREAD

**Issue by ORESoftware** [JavaEden/Orchid#230]
I think many people would agree that JavaDocs aren't very helpful - they only help when you really need to find something using a search engine and ctrl-f.

Say I have a simple Java library like so:

```java
public class Utils {

 @Example("some-local-file.md")
 static interface Bar {}

 @Example("some-other-local-file.md")
 public static void foo(Bar b) {...}

 @Example("some-other-local-file.md")
 public static void bar(){...}

}
```

I am looking to add some annotations/comments to the static methods on the class so I can generate some html or markdown and add examples of how to use each static method.

Is this this right documentation generator for this task? I don't see anything in the readme on how to automatically generate HTML/Markdown for each method on a class or whatnot. I mean obviously there should be some annotations in the .java files that tells the generator what to generate.

**Comment by cjbrooks12** [comment]
This is definitely getting into the more advanced Orchid usage, but the short answer is that what you're wanting is totally possible if you use Javadoc comment tags instead of Annotations. Ideally, Annotations are structures for meta-programming and really shouldn't be used for this kind of documentation, but Orchid's Javadoc comments have what you need instead.

Basically, using Pebble templates, what you're wanting to do is:

1) use the `findAll()` function to lookup all Javadoc class pages in your site
2) Loop through all the methods of all those classes
3) Loop through all the _tags_ on all those methods. 
4) If it has the `example` tag, do what you want with that method

Here's an example of how this might look, such as in a static page like `pages/utils.md`:

```jijna
{% set classPages = findAll(collectionType='javadoc', collectionId='classes') %}

{% for classPage in classPages %}
    <h2>{{classPage.title}}</h2>

    {% for method in classPage.classDoc.methods %}
        <pre><code>{{method.simpleSignature}}</code></pre>

        {% for entry in method.tags %}
            {% if entry.key == 'example' %}
                {{ entry.value.text | load | raw }}
            {% endif %}
       {% endfor %}
   {% endfor %}
{% endfor %}
```

Depending on what exactly you are wanting for the documentation, what kind of filtering should be on those classes/methods, you may want to put that logic inside a custom TemplateTag.
