### ISSUE TITLE
Create netlify app with maven instead of gradle

### ISSUE THREAD

**Issue by ORESoftware** [JavaEden/Orchid#231]
When I click the  button: "Deploy to Netlify" it takes me here
https://app.netlify.com/start/deploy?repository=https://github.com/JavaEden/OrchidStarter

and when I follow the steps, it gives me a gradle project, which I created here:
https://github.com/ORESoftware/OrchidStarter

but this is gradle based - I am looking for something maven based if possible :) thanks, awesome work.

**Comment by cjbrooks12** [comment]
Yup, Maven is fully supported with Orchid. Since the directory structure is the same between Maven and Gradle, all you need is the pom with the Orchid plugin in it.

Here are the docs for using the Maven plugin: https://orchid.netlify.com/wiki/user-manual/getting-started/quickstart#maven

You can also find an example pom in the JavaEden/OrchidTutorials repository, all tutorial projects include the relevant Gradle and Maven build scripts. https://github.com/JavaEden/OrchidTutorials/blob/master/07/pom.xml
