### ISSUE TITLE
Orchid Site generation seems to pick up the root README.md

### ISSUE THREAD

**Issue by dkowis** [JavaEden/Orchid#257]
I don't know if that's intentional, but it seems like it should only grab markdown files from within the Orchid source path.

It makes it a little awkward to have a repository readme, and then it shows up in the blog too.

**Comment by cjbrooks12** [comment]
It is intentional, but it is a very special, limited case. Only the [readme](https://github.com/JavaEden/Orchid/blob/dev/OrchidCore/src/main/kotlin/com/eden/orchid/impl/themes/components/ReadmeComponent.kt) and [license](https://github.com/JavaEden/Orchid/blob/dev/OrchidCore/src/main/kotlin/com/eden/orchid/impl/themes/components/LicenseComponent.kt) files can be loaded in this way, and they are explicitly added with the `readme` and `license` Components.

The idea behind having these special cases is that Orchid is designed to be especially good for project documentation, and has several goodies like this to make it easier to use for that goal.

**Comment by dkowis** [comment]
Ah that's a good idea. Kinda lousy for a blog/website though :( Is there a way to toggle it off for that purpose, or should I use a different site engine? (that's fine BTW.)

**Comment by cjbrooks12** [comment]
Definitely don't use another site engine! 😉 Nearly everything in Orchid is in some way able to be changed, augmented, or replaced, so if there's other strange "quirks" you run into that you don't want, just reach out and I can help you figure out how to fix it.

But for this situation, just remove the `readme` Component and you're good-to-go. The `readme` component is never applied automatically, so somewhere in your site's sources, it is being applied. For the OrchidStarter repo, [this is the line to remove](https://github.com/JavaEden/OrchidStarter/blob/master/src/orchid/resources/homepage.md#L5). Just find the similar line in your site and take it out, and no more README!

**Comment by dkowis** [comment]
Aha, derp. I went looking for that and didn't find it. Also didn't find any obvious README bits in the docs. That works perfectly! Thanks.

Also I asked if I should use a different just to make sure I wasn't trying to bend a tool not built for site/blogging into doing that, and I'd have a bad time along the way :) Thanks for your help!

**Comment by cjbrooks12** [comment]
You definitely aren't being Orchid to something it wasn't built for; Orchid was designed from the beginning with blogging in mind, along with wikis and Javadoc-like code documentation, and getting all of them to play nicely with each other. So while I am definitely focusing on the documentation side of things, it is very well-suited for blogs. I use Orchid for my own [personal blog and gallery](http://caseyjbrooks.com/), which I migrated from Blogger and DeviantArt (see source [here](https://github.com/cjbrooks12/caseyjbrooks)).

Some of Orchid's main sources of inspiration are from the best blogging tools out there today: Jekyll's content management (file/folder structure, post expiry), Hugo's taxonomies (for making tag/category archives), and Wordpress's theming system (seamlessly change themes, custom page templates per post category). 

At this time, you might find other tools a better fit for blogging just because of the availability of more plugins and themes and more resources for learning, but if you're looking to go DIY I think you'll find Orchid to be easier to manage in the long-term or with larger amounts of content.

Orchid's unique, [hierarchical configuration management](https://orchid.netlify.com/wiki/user-manual/content-management/archetypes) makes it easy to keep all your configuration in sync and easy to change in the future. Plus, if you like a CMS for editing, Orchid can build a [NetlifyCMS](https://orchid.netlify.com/plugins/OrchidNetlifyCMS) and will do all its config for you, including surfacing the available "shortcodes" and components available to you (even custom ones you might want to build for yourself). Plus, the [OrchidPosts plugin](https://orchid.netlify.com/plugins/OrchidPosts), in addition to doing normal blog post management, also creates RSS feeds and sitemaps for easy SEO.

**Comment by cjbrooks12** [comment]
Haha, that turned into way more of a "sales pitch" than I anticipated. All that to say, blogging is very much at the forefront of the development of Orchid, and will always continue to be.

**Comment by dkowis** [comment]
Cool! I'm coming from (middleman)[https://middlemanapp.com] which seems to be getting long in the tooth, and not keeping up with the upstream changes. Hugo seems to be the most popular, but I don't know go all that well, and the language kinda rubs me the wrong way. 

Kotlin and the JVM ecosystem I'm quite familiar with, so I thought I could use this and help out with it. Glad to hear that this is right up my alley!

**Comment by dkowis** [comment]
I can close this now, btw. The README bit is super easy to fix.

**Comment by cjbrooks12** [comment]
That's great to hear! When you get the site moved over and launched, feel free to add a link to [Orchid's README](https://github.com/JavaEden/Orchid#example-orchid-sites). I'm also working on a docs overhaul and would like to start building a showcase of sites using Orchid and would love to feature it there!
