### ISSUE TITLE
Access the project version

### ISSUE THREAD

**Issue by DanySK** [JavaEden/Orchid#318]
Hi, is there any way I can access the current version when writing a wiki file? Ideally, I'd like it to work inside `summary.md`.
I could go manually and write a Gradle task that substitutes some token with the current project version, but I'd prefer not to have to hack it this way

thanks

**Comment by cjbrooks12** [comment]
You can use `{{ site.version }}` to get your project's version, and `{{ site.orchidVersion }}` to get the version of Orchid. 

In general, if you're writing Gradle tasks to preprocess your content or anything like that, you're probably doing it wrong, and you could either use existing Orchid functionality or make some kind of custom plugin to do what you want in a better way.

**Comment by DanySK** [comment]
Thanks @cjbrooks12 
Are these calls documented anywhere?

Anyway, if used within `summary.md` in a wiki, produces `{ }` as output. Works within "normal" pages, though.

**Comment by cjbrooks12** [comment]
It's available on any content page that is _precompiled_, which happens when the page has a Front Matter header (even if it's empty). By adding the pairs of triple-dashes to the top of the wiki page, it will be precompiled with Pebble before it gets processed as Markdown, and you can inject anything you want in there. See docs on [Precompiling](https://orchid.netlify.com/wiki/user-manual/core-concepts/precompiling) for more on that.

As for these properties, they're not specifically or thoroughly documented, but these two properties are mentioned in one of the tutorials [here](https://orchid.netlify.com/wiki/learn/tutorials/link-all-the-things#site-global-variable).

**Comment by DanySK** [comment]
Works like a charm. Thanks.
